name: workflow_dispatch
on:
  workflow_dispatch:
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
    - name: echo workflow_dispatch_test
      run: do echo workflow_dispatch_test; sleep 180; done
